name: Update File List

on:
  repository_dispatch:
    types:
      - trigger-update

jobs:
  update-file-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Script
        env:
          MY_GITHUB_TOKEN: ${{ MY_GITHUB_TOKEN }}
        run: |
          python update_file_list.py
